version: '3.8'
services:
  my_ubuntu:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./my-project:/app
    command: sleep infinity
    stdin_open: true
    tty: true
